import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState, AppThunk } from "../../app/store";
import {
  deleteImageAsync,
  uploadImageAsync,
} from "../../services/image.service";

export interface ImageState {
  data: any;
  loading: boolean;
}

const initialState: ImageState = {
  data: {},
  loading: false,
};

export const imageSlice = createSlice({
  name: "image",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(uploadImageAsync.fulfilled, (state, action) => {
          state.loading = false;
      })
      .addCase(uploadImageAsync.pending, (state, action) => {
        state.loading = true;
      })
      .addCase(uploadImageAsync.rejected, (state) => {})
      .addCase(deleteImageAsync.fulfilled, (state, action) => {
      })
      .addCase(deleteImageAsync.rejected, (state) => {});
  },
});

export const selectImage = (state: RootState) => state.image;

export default imageSlice.reducer;
