import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState, AppThunk } from "../../app/store";

export interface AmenitieState {
  amenitie?: any;
  loading: boolean;
}

const initialState: AmenitieState = {
  amenitie: null,
  loading: false,
};

export const amenitieSlice = createSlice({
  name: "amenitie",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    // builder
    //   .addCase(getAccountAsync.fulfilled, (state, action) => {
    //     const { account } = action.payload?.data;
    //     state.account = account;
    //   })
  },
});

// export const {  } = amenitieSlice.actions;

export const selectAccount = (state: RootState) => state.account;

export default amenitieSlice.reducer;
