import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState, AppThunk } from "../../app/store";
import { getAccountAsync } from "../../services/account.service";

export interface UserState {
  data: any;
}

const initialState: UserState = {
  data: {},
};

export const accountSlice = createSlice({
  name: "user",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getAccountAsync.fulfilled, (state, action) => {
        return action.payload;
      })
      .addCase(getAccountAsync.rejected, (state) => {});
  },
});

export default accountSlice.reducer;
