import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState, AppThunk } from "../../app/store";
import { getCategoriesAsync } from "../../services/category.service";

export interface ImageState {
  data: any;
  loading: boolean;
}

const initialState: ImageState = {
  data: {},
  loading: false,
};

export const categorySlice = createSlice({
  name: "category",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getCategoriesAsync.fulfilled, (state, action) => {})
      .addCase(getCategoriesAsync.pending, (state, action) => {});
  },
});

export default categorySlice.reducer;
